resources:
  - url: http://127.0.0.1:5000/lirr-card.js
    type: module
views:
  - cards:
      - type: custom:lirr-card
        name: LIRR Card Development
        entity: sun.sun
        test_gui: true
