name: 'Build'

on:
  push:
    branches:
      - main
      - bug/try-to-fix-builds
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build
        run: |
          npm install
          npm run build
