name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      # Build
      - name: Build the file
        run: |
          npm install
          npm run build

      # Upload build file to the release as an asset.
      # TODO: what? does this work? where would I want to upload?
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/lirr-card/lirr-card/dist/lirr-card.js
          asset_name: lirr-card.js
          tag: ${{ github.ref }}
          overwrite: true
